### ISSUE TITLE
Vimeo videos responding with 500 error in web app

### ISSUE THREAD

**Issue by ericmatthys** [plexinc-plugins/Vimeo.bundle#15]
```xml
<Response code="2001" status="This media is not currently available."/>
```

 1. Go to Staff Picks in the web app
 2. Play a video
 3. Observe 500 error

**Comment by ericmatthys** [comment]
Looks like this is fixed elsewhere.

**Comment by sander1** [comment]
Probably fixed somewhere in https://github.com/plexinc-plugins/Services.bundle/compare/cc14573635489f5ef6ee8361357e1b82415bd02e...5a6a0dbabf72c7b772584d95f6101c31918dd54c
