### ISSUE TITLE
Channels and Group sections of channel showing no results

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Vimeo.bundle#16]
Now it seems that the Channels and Group sections list the categories, but none of these categories show any results.

**Comment by shopgirl284** [comment]
Vimeo now breaks up its videos into categories, channels and groups. Considering that the My Stuff has also been broken for awhile, to quickly fix this issue and the channel, the best option is to rewrite the channel to reflect the sections that can presently be accessed.

Since the channel has been around for awhile, the code of the plugin would also benefit from some cleaning up and simplification to make it easier to maintain in the future.

**Comment by shopgirl284** [comment]
Submitted PR #17 that updates code and removes MyStuff since it no longer works

**Comment by sander1** [comment]
Fixed with ce7e84e5bd6af13631b65f2d8a37080923aae5af
